# Generated by Django 6.0.7 on 2026-08-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeprofile',
            old_name='cnin',
            new_name='cnic',
        ),
    ]
