# Generated by Django 6.0.7 on 2026-08-06 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='conductor',
            field=models.ForeignKey(limit_choices_to={'role': 'CONDUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_conducted', to='users.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_driven', to='users.employeeprofile'),
        ),
    ]
