# Generated by Django 6.0.7 on 2026-08-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_trip_conductor_alter_trip_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfig',
            name='payment_option_1',
            field=models.CharField(blank=True, default='Bank Transfer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentconfig',
            name='payment_option_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
