# Generated by Django 6.0.7 on 2026-08-07 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_paymentconfig_payment_option_1_and_more'),
        ('users', '0002_rename_cnin_employeeprofile_cnic'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('ticket_status__in', ['CANCELLED_USER', 'CANCELLED_COMPANY', 'CANCELLED']), _negated=True), fields=('trip', 'seat_number'), name='unique_active_seat_per_trip'),
        ),
    ]
