# Generated by Django 6.0.7 on 2026-08-07 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_alter_ticket_unique_together_and_more'),
        ('users', '0002_rename_cnin_employeeprofile_cnic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='conductor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'CONDUCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_conducted', to='users.employeeprofile'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='driver',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'DRIVER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_driven', to='users.employeeprofile'),
        ),
        migrations.CreateModel(
            name='TripExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('FUEL', 'Fuel / Diesel'), ('TOLL', 'Toll Tax'), ('MAINT', 'Emergency Maintenance'), ('MEAL', 'Staff Meals'), ('CHALLAN', 'Route Fines / Challan'), ('OTHER', 'Other / Misc')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, help_text='Optional details or receipt numbers.')),
                ('date_logged', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employeeprofile')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='bookings.trip')),
            ],
        ),
    ]
