# Generated by Django 6.0.7 on 2026-08-17 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_alter_trip_conductor_alter_trip_driver_tripexpense'),
        ('users', '0002_rename_cnin_employeeprofile_cnic'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(help_text='e.g., Bhera Rest Area, Faizabad Interchange', max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('logged_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employeeprofile')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_logs', to='bookings.trip')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
