# Generated by Django 6.0.7 on 2026-08-21 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_triptracking'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fare', models.DecimalField(decimal_places=2, default=500.0, help_text='Fixed boarding charge (Rs.)', max_digits=10)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=5.5, help_text='Rate per kilometer (Rs.)', max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dynamic Pricing Configuration',
                'verbose_name_plural': 'Dynamic Pricing Configurations',
            },
        ),
        migrations.CreateModel(
            name='RouteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.IntegerField(help_text='1 for Origin, 2 for Mid-point, etc.')),
                ('distance_from_origin', models.DecimalField(decimal_places=2, default=0.0, help_text='Distance in KM from the absolute start of the route.', max_digits=7)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bookings.location')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='bookings.route')),
            ],
            options={
                'ordering': ['stop_order'],
                'unique_together': {('route', 'location')},
            },
        ),
    ]
