# Generated by Django 6.0.7 on 2026-08-21 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_pricingconfig_routenode'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassengerComplaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('MAINTENANCE', 'Seat/Screen/AC Issue'), ('HARASSMENT', 'Harassment/Safety concern'), ('STAFF', 'Staff Behavior'), ('OTHER', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='bookings.ticket')),
            ],
        ),
    ]
