# Generated by Django 6.0.7 on 2026-08-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_passengercomplaint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FareCalculation',
        ),
    ]
