# Generated by Django 6.0.7 on 2026-08-21 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_delete_farecalculation'),
        ('users', '0002_rename_cnin_employeeprofile_cnic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='e.g., TICKET_DELETED, REFUND_PROCESSED', max_length=100)),
                ('description', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='routenode',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_ends', to='bookings.location'),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_starts', to='bookings.location'),
        ),
        migrations.AddConstraint(
            model_name='routenode',
            constraint=models.UniqueConstraint(fields=('route', 'location'), name='unique_location_per_route'),
        ),
        migrations.AddConstraint(
            model_name='routenode',
            constraint=models.UniqueConstraint(fields=('route', 'stop_order'), name='unique_stop_order_per_route'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='actor',
            field=models.ForeignKey(help_text='The employee who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.employeeprofile'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookings.ticket'),
        ),
    ]
