# Generated by Django 6.0.7 on 2026-08-25 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0011_auditlog_alter_routenode_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'Buses'},
        ),
    ]
