# Generated by Django 6.0.7 on 2026-08-25 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0012_alter_bus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='routenode',
            name='travel_time_from_origin',
            field=models.DurationField(default=datetime.timedelta(0), help_text='Format: HH:MM:SS (e.g., 02:30:00 for 2.5 hours from origin). Includes traffic & rest stops.'),
        ),
    ]
