# Generated by Django 6.0.7 on 2026-08-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0013_routenode_travel_time_from_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='arrival_time',
            field=models.TimeField(blank=True, editable=False, null=True),
        ),
    ]
